package sanmateo.avinnovz.com.sanmateoprofile.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import sanmateo.avinnovz.com.sanmateoprofile.dao.PanicContact;
import sanmateo.avinnovz.com.sanmateoprofile.dao.CurrentUser;
import sanmateo.avinnovz.com.sanmateoprofile.dao.LocalGallery;
import sanmateo.avinnovz.com.sanmateoprofile.dao.LocalOfficial;

import sanmateo.avinnovz.com.sanmateoprofile.dao.PanicContactDao;
import sanmateo.avinnovz.com.sanmateoprofile.dao.CurrentUserDao;
import sanmateo.avinnovz.com.sanmateoprofile.dao.LocalGalleryDao;
import sanmateo.avinnovz.com.sanmateoprofile.dao.LocalOfficialDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig panicContactDaoConfig;
    private final DaoConfig currentUserDaoConfig;
    private final DaoConfig localGalleryDaoConfig;
    private final DaoConfig localOfficialDaoConfig;

    private final PanicContactDao panicContactDao;
    private final CurrentUserDao currentUserDao;
    private final LocalGalleryDao localGalleryDao;
    private final LocalOfficialDao localOfficialDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        panicContactDaoConfig = daoConfigMap.get(PanicContactDao.class).clone();
        panicContactDaoConfig.initIdentityScope(type);

        currentUserDaoConfig = daoConfigMap.get(CurrentUserDao.class).clone();
        currentUserDaoConfig.initIdentityScope(type);

        localGalleryDaoConfig = daoConfigMap.get(LocalGalleryDao.class).clone();
        localGalleryDaoConfig.initIdentityScope(type);

        localOfficialDaoConfig = daoConfigMap.get(LocalOfficialDao.class).clone();
        localOfficialDaoConfig.initIdentityScope(type);

        panicContactDao = new PanicContactDao(panicContactDaoConfig, this);
        currentUserDao = new CurrentUserDao(currentUserDaoConfig, this);
        localGalleryDao = new LocalGalleryDao(localGalleryDaoConfig, this);
        localOfficialDao = new LocalOfficialDao(localOfficialDaoConfig, this);

        registerDao(PanicContact.class, panicContactDao);
        registerDao(CurrentUser.class, currentUserDao);
        registerDao(LocalGallery.class, localGalleryDao);
        registerDao(LocalOfficial.class, localOfficialDao);
    }
    
    public void clear() {
        panicContactDaoConfig.getIdentityScope().clear();
        currentUserDaoConfig.getIdentityScope().clear();
        localGalleryDaoConfig.getIdentityScope().clear();
        localOfficialDaoConfig.getIdentityScope().clear();
    }

    public PanicContactDao getPanicContactDao() {
        return panicContactDao;
    }

    public CurrentUserDao getCurrentUserDao() {
        return currentUserDao;
    }

    public LocalGalleryDao getLocalGalleryDao() {
        return localGalleryDao;
    }

    public LocalOfficialDao getLocalOfficialDao() {
        return localOfficialDao;
    }

}
