package sanmateo.avinnovz.com.sanmateoprofile.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCAL_OFFICIAL.
 */
public class LocalOfficial {

    private Long id;
    private Integer officialId;
    private String createdAt;
    private String updatedAt;
    private String deletedAt;
    private String firstName;
    private String lastName;
    private String nickName;
    private String position;
    private String background;
    private String pic;
    private String status;

    public LocalOfficial() {
    }

    public LocalOfficial(Long id) {
        this.id = id;
    }

    public LocalOfficial(Long id, Integer officialId, String createdAt, String updatedAt, String deletedAt, String firstName, String lastName, String nickName, String position, String background, String pic, String status) {
        this.id = id;
        this.officialId = officialId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.firstName = firstName;
        this.lastName = lastName;
        this.nickName = nickName;
        this.position = position;
        this.background = background;
        this.pic = pic;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getOfficialId() {
        return officialId;
    }

    public void setOfficialId(Integer officialId) {
        this.officialId = officialId;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(String deletedAt) {
        this.deletedAt = deletedAt;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
