package sanmateo.avinnovz.com.sanmateoprofile.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import sanmateo.avinnovz.com.sanmateoprofile.dao.PanicContact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PANIC_CONTACT.
*/
public class PanicContactDao extends AbstractDao<PanicContact, Long> {

    public static final String TABLENAME = "PANIC_CONTACT";

    /**
     * Properties of entity PanicContact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ContactName = new Property(1, String.class, "contactName", false, "CONTACT_NAME");
        public final static Property ContactNo = new Property(2, String.class, "contactNo", false, "CONTACT_NO");
    };


    public PanicContactDao(DaoConfig config) {
        super(config);
    }
    
    public PanicContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PANIC_CONTACT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTACT_NAME' TEXT," + // 1: contactName
                "'CONTACT_NO' TEXT);"); // 2: contactNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PANIC_CONTACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PanicContact entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String contactName = entity.getContactName();
        if (contactName != null) {
            stmt.bindString(2, contactName);
        }
 
        String contactNo = entity.getContactNo();
        if (contactNo != null) {
            stmt.bindString(3, contactNo);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PanicContact readEntity(Cursor cursor, int offset) {
        PanicContact entity = new PanicContact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // contactName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // contactNo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PanicContact entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContactName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContactNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PanicContact entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PanicContact entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
